#!/bin/sh
STORAGE_LOCAL_PATH=/prometheus
if [ -d /mnt/mesos/sandbox/prometheus ]; then
  STORAGE_LOCAL_PATH=/mnt/mesos/sandbox/prometheus
fi
/bin/srv-lookup -srv "$NODE_EXPORTER_SRV" -out "/etc/prometheus/node_exporter.json" -loop -time ${SRV_REFRESH_INTERVAL:-60} &
/bin/prometheus \
  -config.file=/etc/prometheus/prometheus.yml \
  -storage.local.path=$STORAGE_LOCAL_PATH \
  -web.console.libraries=/etc/prometheus/console_libraries \
  -web.console.templates=/etc/prometheus/consoles \
  -alertmanager.url=${ALERT_MANAGER_URI:-http://prometheusalertmanager.marathon.l4lb.thisdcos.directory:9093} \
  "$@"
