#!/bin/sh
set -o errexit -o nounset -o pipefail

STORAGE_LOCAL_PATH=/prometheus
[ -d /mnt/mesos/sandbox/prometheus ] && STORAGE_LOCAL_PATH=/mnt/mesos/sandbox/prometheus
mkdir -p $STORAGE_LOCAL_PATH/server $STORAGE_LOCAL_PATH/alertmanager

/bin/mkalertmanagercfg "/etc/prometheus/alertmanager.yml"

if [ -n "${RULES-}" ]; then
  echo "Writing ENV set RULES to /etc/prometheus/prometheus.rules"
  echo -e "$RULES" > /etc/prometheus/prometheus.rules
fi

if [ -n "${NODE_EXPORTER_SRV-}" ]; then
  /bin/srv2file_sd -srv "$NODE_EXPORTER_SRV" -out "/etc/prometheus/node_exporter.json" -loop -time ${SRV_REFRESH_INTERVAL:-60} &
fi
if [ -n "${CADVISOR_SRV-}" ]; then
  /bin/srv2file_sd -srv "$CADVISOR_SRV" -out "/etc/prometheus/cadvisor.json" -loop -time ${SRV_REFRESH_INTERVAL:-60} &
fi

/bin/alertmanager -config.file "/etc/prometheus/alertmanager.yml" \
                  -storage.path "$STORAGE_LOCAL_PATH/alertmanager" &
/bin/prometheus \
  -config.file /etc/prometheus/prometheus.yml \
  -storage.local.path $STORAGE_LOCAL_PATH/server \
  -web.console.libraries /etc/prometheus/console_libraries \
  -web.console.templates /etc/prometheus/consoles \
  -web.external-url "${EXTERNAL_URI:-http://prometheusserver.marathon.l4lb.thisdcos.directory:9090}" \
  -alertmanager.url "${ALERT_MANAGER_URI:-http://localhost:9093}" \
  "$@"
